version: '3.8'
services:
  server:
    image: ghcr.io/jasonlaguidice/mithia-server:latest
    command: ["/bin/bash", "-c", "cd /home/RTK/rtk && ./start-mithia-servers && tail -f /dev/null"]
    restart: always
    ports:
      - "2000:2000"  # Login Server
      - "2001:2001"  # Map Server
      - "2005:2005"  # Character Server
    volumes:
      - "rtk_data:/home/RTK/rtk"
      - "rtklua_data:/home/RTK/rtklua"
      - "rtkmaps_data:/home/RTK/rtkmaps"
      - "./data/backups:/home/RTK/backups"
      - "./data/logs:/home/RTK/rtk/logs"

  database:
    image: mysql/mysql-server:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'definitelyChangeMe'
      MYSQL_USER: 'rtk'
      MYSQL_PASSWORD: 'changeMe'
      MYSQL_DATABASE: 'RTK'
    ports:
      - "3306:3306"
    volumes:
      - "./database/scripts:/docker-entrypoint-initdb.d" # Every script in docker-entrypoint-initdb.d is executed in alphabetical order as soon as the container starts
      - "./data/mysql:/var/lib/mysql"
      - "./data/backups:/backups"

volumes:
  rtk_data:
    driver: local
  rtklua_data:
    driver: local
  rtkmaps_data:
    driver: local
